
default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: toolhero_development

test:
  <<: *default
  database: toolhero_test


production:
  <<: *default
  database: toolhero_production
  username: toolhero
  password: <%= ENV['TOOLHERO_DATABASE_PASSWORD'] %>
